<?php
/**
 * EIU PHP FRAMEWORK
 *
 * @author        成都东联智胜软件有限公司
 * @link          https://www.cneiu.com
 */


namespace test\modules\controllers\admin;


use eiu\abstracts\controller\Controller;


/**
 * 管理控制器
 */
class AdminController extends Controller
{
    public function _index()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}